import Head from "next/head";

export default function Home() {
  return (
    <>
      <Head>
        <title>Home page</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <section className="py-6">
          <div className="container">
            <h1 className="font-heading text-2xl">Im a home page</h1>
          </div>
        </section>
      </main>
    </>
  );
}
