import Head from "next/head";
import BestOffers from "../sections/best-offers";
import Navigation from "../sections/navigation";
import AllGames from "../sections/all-games";
import BuyCrypto from "../sections/buy-crypto";

export default function Home() {
  return (
    <>
      <Head>
        <title>Home page</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

      <BestOffers />

      <Navigation />

      <AllGames />

      <BuyCrypto />
    </>
  );
}
